### ISSUE TITLE
Any support plan changing consistency level when reading cdc log?

### ISSUE THREAD

**Issue by pkgonan** [scylladb/scylla-cdc-source-connector#3]
HI.

Only reading the cdc log on Scylla takes too long, over a few seconds. When reading the cdc log, it seems to query other data centers together. Are there any plans to support a setting that changes the consistency level when reading cdc logs? For example local_quorum, each_quorum.. etc.

[Environment]
```
DC US_WEST_1 => AWS EC2 i3en.6xlarge * 3
DC EU_CENTRAL_1 => AWS EC2 i3en.6xlarge * 3
```

[Config]
```
CREATE KEYSPACE IF NOT EXISTS test_service WITH REPLICATION = {
'class' : 'NetworkTopologyStrategy',
'AWS_US_WEST_1' : 3,
'AWS_EU_CENTRAL_1' : 3
};
```

[SourceConnector Config]
```
  "connector.class": "com.scylladb.cdc.debezium.connector.ScyllaConnector",
  "tasks.max": "3",
  "scylla.cluster.ip.addresses": "'${database_url}'",
  "scylla.user": "'${database_user}'",
  "scylla.password": "'${database_password}'",
  "scylla.name": "cdc-data.test",
  "scylla.table.names": "'${table_include_list}'",
  "scylla.query.time.window.size": "5000",
  "scylla.confidence.window.size": "5000",
  "producer.override.acks": "-1",
  "producer.override.max.in.flight.requests.per.connection": "1",
  "producer.override.compression.type": "snappy",
  "producer.override.linger.ms": "50",
  "producer.override.batch.size": "327680",
  "errors.tolerance": "all",
  "errors.log.enable": "true",
  "errors.log.include.messages": "true",
  "topic.creation.default.replication.factor": "'${replication_factor}'",
  "topic.creation.default.partitions": "11"
```

[Metric]
<img width="1304" alt="스크린샷 2021-04-29 오전 11 27 43" src="https://user-images.githubusercontent.com/15858772/116497518-886f4180-a8e2-11eb-9789-ef69589e2a53.png">

**Comment by avelanarius** [comment]
I see how changing the consistency level is an important missing feature. I'll start working on adding this functionality and I'll ping you once it's done and tested.

**Comment by pkgonan** [comment]
@avelanarius 
I think that there are two points where you need to change the consistency level.

First. Selecting cluster's metadata. (Keyspace : system_distributed)
Second. Selecting cdc log table. (Table : my_keyspace.my_table_scylla_cdc_log)

**Comment by pkgonan** [comment]
Ping?!

**Comment by pkgonan** [comment]
@avelanarius Thanks a lot.
Please publish 1.2.0 version fat jar file to maven repository. (https://search.maven.org/artifact/com.scylladb/scylla-cdc-source-connector/1.0.0/pom)

**Comment by avelanarius** [comment]
I have published the next version to Maven:
https://search.maven.org/artifact/com.scylladb/scylla-cdc-source-connector/1.0.1/pom

as well as pre-built ZIP and JAR files in this repository (links in `README`).
